### ISSUE TITLE
Live Game Fails

### ISSUE THREAD

**Issue by woody3000** [Yuioup/kodi-mlbmc#10]
Running 2.0.76

Trying to play a game produces this in my log file:

>19:57:37 T:140028734854912  NOTICE: [MLBMC-2.0.76]: Selected: Washington Nationals Coverage MSN2-HD
19:57:37 T:140028734854912  NOTICE: [MLBMC-2.0.76]: content: Washington Nationals Coverage MSN2-HD
19:59:31 T:140028734854912   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.mlbmc/default.py", line 153, in <module>
                                                mlbtv.get_mlb_game(event)
                                              File "/storage/.kodi/addons/plugin.video.mlbmc/resources/mlbtv.py", line 290, in get_mlb_game
                                                get_game_url(*sorted_content[ret])
                                              File "/storage/.kodi/addons/plugin.video.mlbmc/resources/mlbtv.py", line 316, in get_game_url
                                                data = get_request(url, urllib.urlencode(values), None)
                                              File "/storage/.kodi/addons/plugin.video.mlbmc/resources/mlb_common.py", line 82, in get_request
                                                response = urllib2.urlopen(req)
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1180, in do_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/httplib.py", line 1030, in getresponse
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/httplib.py", line 407, in begin
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/httplib.py", line 371, in _read_status
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
19:59:31 T:140030752229248   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.mlbmc/?url=&mode=7&name=Washington+0+%40+Miami+1++Top+3&event=14-415167-2015-07-29]

There's also a very long delay between selecting the game feed to play and this error (19:57:37 to 19:59:31)

**Comment by Yuioup** [comment]
Looks like it can't find the game. Did you select a future date? Sometimes it gets confusing that you think you're selecting yesterday's game but you're selecting tonight's game, and it is morning right now (for example).

**Comment by woody3000** [comment]
No it was for yesterday's game (7/29).
